SYSTEM = struct(
%cell config
                  'cellID',   0,...
%antenna config
                  'TxNum',    1,...
                  'RxNum',    2,...
%subframe config
                  'totalRB',  1,...
                  'totalOFDM',    14, ...
                  'SCsPerRB',    12, ...
                  'CP1',    80, ...
                  'CP2',    72, ...
%PRS config
                  'totalRB_PRS',   1 ... 
                  
)