SYSTEM = struct(
%system config
                  'DW',       10e6, ...
%cell config
                  'cellID',   0,...
%physical antenna config
                  'TxNum',    1,...
                  'RxNum',    2,...
%subframe config
                  'totalRB',  1,...
                  'totalOFDM',    14, ...
                  'SCsPerRB',    12, ...
                  'FFTsize',    1024, ...
                  'CP1',    80, ...
                  'CP2',    72, ...
%PBCH config 
                  'PBCHports',    1, ...
%PRS config
                  'totalRB_PRS',   1 ... 
                  
)